version: '3.8'
services:
  api:
    build: ./server
    container_name: dcp_api
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
