version: '3.8'
services:
  api:
    build: ./server
    container_name: dcp_api
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  web:
    build: ./client
    container_name: dcp_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped
