version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: dcp_itcr_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dcp_itcr
    volumes:
      - mongodb_data:/data/db

  server:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/dcp_itcr
      - JWT_SECRET=tu_clave_secreta_muy_segura_para_produccion_cambiar_esto
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb

volumes:
  mongodb_data: