version: '3.8'

services:
  core:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development